steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Image'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/docker-repository/react:$SHORT_SHA', "."]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push to GCR'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/docker-repository/hello-go:$SHORT_SHA']

  - name: 'ubuntu'
    id: 'Tag Override'
    args:
      - bash
      - -c
      - 'sed -i.bk s/latest/$SHORT_SHA/g deployment.yaml'
    dir: 'manifest'

  - name: "gcr.io/cloud-builders/kubectl"
    id: 'kubectl apply'
    args:
      - apply
      - --filename=deployment.yaml
    env:
    - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
    dir: 'manifest'
